name: 'Lighthouse Check'
description: 'Run Lighthouse performance tests with beautiful output and PR comments'

inputs:
  url:
    description: 'URL to test with Lighthouse'
    required: true
  github-token:
    description: 'GitHub token for posting comments'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'build/index.js'

branding:
  icon: 'zap'
  color: 'green'
