name: Deploy to Production

on:
  release:
    types: [released, prereleased]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      deployments: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Production
        id: deploy
        uses: centrifuge/github-actions-lib/apps-v3/actions/deploy-app@main
        with:
          environment: ${{ github.event.action == 'prereleased' && 'staging' || 'production' }}
          build-mode: mainnet
          release-tag: ${{ github.ref_name }}
          app-name: 'launchpad'


