name: Deploy to Development

on:
  push:
    branches: [main]

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run CI Checks
        uses: centrifuge/github-actions-lib/apps-v3/actions/ci-checks@main

  deploy-dev:
    runs-on: ubuntu-latest
    needs: ci-checks
    permissions:
      contents: read
      deployments: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Development
        id: deploy
        uses: centrifuge/github-actions-lib/apps-v3/actions/deploy-app@main
        with:
          environment: dev
          build-mode: testnet
